In [2]:
import pandas as pd
import numpy as np

In [3]:
df=pd.read_csv("SuperStoreOrders.csv")

In [4]:
df.head(5)

,order_id,order_date,ship_date,ship_mode,customer_name,segment,state,country,market,region,...,category,sub_category,product_name,sales,quantity,discount,profit,shipping_cost,order_priority,year
0,AG-2011-2040,1/1/2011,6/1/2011,Standard Class,Toby Braunhardt,Consumer,Constantine,Algeria,Africa,Africa,...,Office Supplies,Storage,"Tenex Lockers, Blue",408,2,0.0,106.140,35.46,Medium,2011
1,IN-2011-47883,1/1/2011,8/1/2011,Standard Class,Joseph Holt,Consumer,New South Wales,Australia,APAC,Oceania,...,Office Supplies,Supplies,"Acme Trimmer, High Speed",120,3,0.1,36.036,9.72,Medium,2011
2,HU-2011-1220,1/1/2011,5/1/2011,Second Class,Annie Thurman,Consumer,Budapest,Hungary,EMEA,EMEA,...,Office Supplies,Storage,"Tenex Box, Single Width",66,4,0.0,29.640,8.17,High,2011
3,IT-2011-3647632,1/1/2011,5/1/2011,Second Class,Eugene Moren,Home Office,Stockholm,Sweden,EU,North,...,Office Supplies,Paper,"Enermax Note Cards, Premium",45,3,0.5,-26.055,4.82,High,2011
4,IN-2011-47883,1/1/2011,8/1/2011,Standard Class,Joseph Holt,Consumer,New South Wales,Australia,APAC,Oceania,...,Furniture,Furnishings,"Eldon Light Bulb, Duo Pack",114,5,0.1,37.770,4.70,Medium,2011

In [5]:
df.info

<bound method DataFrame.info of               order_id  order_date ship_date       ship_mode  \
0         AG-2011-2040    1/1/2011  6/1/2011  Standard Class
1        IN-2011-47883    1/1/2011  8/1/2011  Standard Class
2         HU-2011-1220    1/1/2011  5/1/2011    Second Class
3      IT-2011-3647632    1/1/2011  5/1/2011    Second Class
4        IN-2011-47883    1/1/2011  8/1/2011  Standard Class
...                ...         ...       ...             ...
51285   CA-2014-115427  31-12-2014  4/1/2015  Standard Class
51286     MO-2014-2560  31-12-2014  5/1/2015  Standard Class
51287   MX-2014-110527  31-12-2014  2/1/2015    Second Class
51288   MX-2014-114783  31-12-2014  6/1/2015  Standard Class
51289   CA-2014-156720  31-12-2014  4/1/2015  Standard Class

          customer_name      segment             state        country  market  \
0       Toby Braunhardt     Consumer       Constantine        Algeria  Africa
1           Joseph Holt     Consumer   New South Wales      Australia    APAC
2         Annie Thurman     Consumer          Budapest        Hungary    EMEA
3          Eugene Moren  Home Office         Stockholm         Sweden      EU
4           Joseph Holt     Consumer   New South Wales      Australia    APAC
...                 ...          ...               ...            ...     ...
51285        Erica Bern    Corporate        California  United States      US
51286         Liz Preis     Consumer  Souss-Massa-Draâ        Morocco  Africa
51287  Charlotte Melton     Consumer           Managua      Nicaragua   LATAM
51288     Tamara Dahlen     Consumer         Chihuahua         Mexico   LATAM
51289     Jill Matthias     Consumer          Colorado  United States      US

        region  ...         category sub_category  \
0       Africa  ...  Office Supplies      Storage
1      Oceania  ...  Office Supplies     Supplies
2         EMEA  ...  Office Supplies      Storage
3        North  ...  Office Supplies        Paper
4      Oceania  ...        Furniture  Furnishings
...        ...  ...              ...          ...
51285     West  ...  Office Supplies      Binders
51286   Africa  ...  Office Supplies      Binders
51287  Central  ...  Office Supplies       Labels
51288    North  ...  Office Supplies       Labels
51289     West  ...  Office Supplies    Fasteners

                                          product_name sales quantity  \
0                                  Tenex Lockers, Blue   408        2
1                             Acme Trimmer, High Speed   120        3
2                              Tenex Box, Single Width    66        4
3                          Enermax Note Cards, Premium    45        3
4                           Eldon Light Bulb, Duo Pack   114        5
...                                                ...   ...      ...
51285  Cardinal Slant-D Ring Binder, Heavy Gauge Vinyl    14        2
51286          Wilson Jones Hole Reinforcements, Clear     4        1
51287           Hon Color Coded Labels, 5000 Label Set    26        3
51288           Hon Legal Exhibit Labels, Alphabetical     7        1
51289                              Bagged Rubber Bands     3        3

       discount    profit  shipping_cost  order_priority  year
0           0.0  106.1400          35.46          Medium  2011
1           0.1   36.0360           9.72          Medium  2011
2           0.0   29.6400           8.17            High  2011
3           0.5  -26.0550           4.82            High  2011
4           0.1   37.7700           4.70          Medium  2011
...         ...       ...            ...             ...   ...
51285       0.2    4.5188           0.89          Medium  2014
51286       0.0    0.4200           0.49          Medium  2014
51287       0.0   12.3600           0.35          Medium  2014
51288       0.0    0.5600           0.20          Medium  2014
51289       0.2   -0.6048           0.17          Medium  2014

[51290 rows x 21 columns]>

In [6]:
df.columns

Index(['order_id', 'order_date', 'ship_date', 'ship_mode', 'customer_name',
       'segment', 'state', 'country', 'market', 'region', 'product_id',
       'category', 'sub_category', 'product_name', 'sales', 'quantity',
       'discount', 'profit', 'shipping_cost', 'order_priority', 'year'],
      dtype='object')

In [7]:
df.describe

<bound method NDFrame.describe of               order_id  order_date ship_date       ship_mode  \
0         AG-2011-2040    1/1/2011  6/1/2011  Standard Class
1        IN-2011-47883    1/1/2011  8/1/2011  Standard Class
2         HU-2011-1220    1/1/2011  5/1/2011    Second Class
3      IT-2011-3647632    1/1/2011  5/1/2011    Second Class
4        IN-2011-47883    1/1/2011  8/1/2011  Standard Class
...                ...         ...       ...             ...
51285   CA-2014-115427  31-12-2014  4/1/2015  Standard Class
51286     MO-2014-2560  31-12-2014  5/1/2015  Standard Class
51287   MX-2014-110527  31-12-2014  2/1/2015    Second Class
51288   MX-2014-114783  31-12-2014  6/1/2015  Standard Class
51289   CA-2014-156720  31-12-2014  4/1/2015  Standard Class

          customer_name      segment             state        country  market  \
0       Toby Braunhardt     Consumer       Constantine        Algeria  Africa
1           Joseph Holt     Consumer   New South Wales      Australia    APAC
2         Annie Thurman     Consumer          Budapest        Hungary    EMEA
3          Eugene Moren  Home Office         Stockholm         Sweden      EU
4           Joseph Holt     Consumer   New South Wales      Australia    APAC
...                 ...          ...               ...            ...     ...
51285        Erica Bern    Corporate        California  United States      US
51286         Liz Preis     Consumer  Souss-Massa-Draâ        Morocco  Africa
51287  Charlotte Melton     Consumer           Managua      Nicaragua   LATAM
51288     Tamara Dahlen     Consumer         Chihuahua         Mexico   LATAM
51289     Jill Matthias     Consumer          Colorado  United States      US

        region  ...         category sub_category  \
0       Africa  ...  Office Supplies      Storage
1      Oceania  ...  Office Supplies     Supplies
2         EMEA  ...  Office Supplies      Storage
3        North  ...  Office Supplies        Paper
4      Oceania  ...        Furniture  Furnishings
...        ...  ...              ...          ...
51285     West  ...  Office Supplies      Binders
51286   Africa  ...  Office Supplies      Binders
51287  Central  ...  Office Supplies       Labels
51288    North  ...  Office Supplies       Labels
51289     West  ...  Office Supplies    Fasteners

                                          product_name sales quantity  \
0                                  Tenex Lockers, Blue   408        2
1                             Acme Trimmer, High Speed   120        3
2                              Tenex Box, Single Width    66        4
3                          Enermax Note Cards, Premium    45        3
4                           Eldon Light Bulb, Duo Pack   114        5
...                                                ...   ...      ...
51285  Cardinal Slant-D Ring Binder, Heavy Gauge Vinyl    14        2
51286          Wilson Jones Hole Reinforcements, Clear     4        1
51287           Hon Color Coded Labels, 5000 Label Set    26        3
51288           Hon Legal Exhibit Labels, Alphabetical     7        1
51289                              Bagged Rubber Bands     3        3

       discount    profit  shipping_cost  order_priority  year
0           0.0  106.1400          35.46          Medium  2011
1           0.1   36.0360           9.72          Medium  2011
2           0.0   29.6400           8.17            High  2011
3           0.5  -26.0550           4.82            High  2011
4           0.1   37.7700           4.70          Medium  2011
...         ...       ...            ...             ...   ...
51285       0.2    4.5188           0.89          Medium  2014
51286       0.0    0.4200           0.49          Medium  2014
51287       0.0   12.3600           0.35          Medium  2014
51288       0.0    0.5600           0.20          Medium  2014
51289       0.2   -0.6048           0.17          Medium  2014

[51290 rows x 21 columns]>

In [8]:
print(df.shape)
print(df.columns.tolist())

(51290, 21)
['order_id', 'order_date', 'ship_date', 'ship_mode', 'customer_name', 'segment', 'state', 'country', 'market', 'region', 'product_id', 'category', 'sub_category', 'product_name', 'sales', 'quantity', 'discount', 'profit', 'shipping_cost', 'order_priority', 'year']

In [9]:
df.head()

,order_id,order_date,ship_date,ship_mode,customer_name,segment,state,country,market,region,...,category,sub_category,product_name,sales,quantity,discount,profit,shipping_cost,order_priority,year
0,AG-2011-2040,1/1/2011,6/1/2011,Standard Class,Toby Braunhardt,Consumer,Constantine,Algeria,Africa,Africa,...,Office Supplies,Storage,"Tenex Lockers, Blue",408,2,0.0,106.140,35.46,Medium,2011
1,IN-2011-47883,1/1/2011,8/1/2011,Standard Class,Joseph Holt,Consumer,New South Wales,Australia,APAC,Oceania,...,Office Supplies,Supplies,"Acme Trimmer, High Speed",120,3,0.1,36.036,9.72,Medium,2011
2,HU-2011-1220,1/1/2011,5/1/2011,Second Class,Annie Thurman,Consumer,Budapest,Hungary,EMEA,EMEA,...,Office Supplies,Storage,"Tenex Box, Single Width",66,4,0.0,29.640,8.17,High,2011
3,IT-2011-3647632,1/1/2011,5/1/2011,Second Class,Eugene Moren,Home Office,Stockholm,Sweden,EU,North,...,Office Supplies,Paper,"Enermax Note Cards, Premium",45,3,0.5,-26.055,4.82,High,2011
4,IN-2011-47883,1/1/2011,8/1/2011,Standard Class,Joseph Holt,Consumer,New South Wales,Australia,APAC,Oceania,...,Furniture,Furnishings,"Eldon Light Bulb, Duo Pack",114,5,0.1,37.770,4.70,Medium,2011

In [10]:
df.isnull().sum()

order_id          0
order_date        0
ship_date         0
ship_mode         0
customer_name     0
segment           0
state             0
country           0
market            0
region            0
product_id        0
category          0
sub_category      0
product_name      0
sales             0
quantity          0
discount          0
profit            0
shipping_cost     0
order_priority    0
year              0
dtype: int64

In [11]:
df.duplicated().sum()

np.int64(0)

In [12]:
df.dtypes

order_id           object
order_date         object
ship_date          object
ship_mode          object
customer_name      object
segment            object
state              object
country            object
market             object
region             object
product_id         object
category           object
sub_category       object
product_name       object
sales              object
quantity            int64
discount          float64
profit            float64
shipping_cost     float64
order_priority     object
year                int64
dtype: object

In [19]:
df["category"].value_counts()

category
Office Supplies    31273
Technology         10141
Furniture           9876
Name: count, dtype: int64

In [28]:
df.describe()

,sales,quantity,discount,profit,shipping_cost,year
count,51290.000000,51290.000000,51290.000000,51290.000000,51290.000000,51290.000000
mean,246.498440,3.476545,0.142908,28.641740,26.375915,2012.777208
std,487.567175,2.278766,0.212280,174.424113,57.296804,1.098931
min,0.000000,1.000000,0.000000,-6599.978000,0.000000,2011.000000
25%,31.000000,2.000000,0.000000,0.000000,2.610000,2012.000000
50%,85.000000,3.000000,0.000000,9.240000,7.790000,2013.000000
75%,251.000000,5.000000,0.200000,36.810000,24.450000,2014.000000
max,22638.000000,14.000000,0.850000,8399.976000,933.570000,2014.000000

In [27]:
df[["sales", "profit", "quantity", "discount"]].describe()

              sales        profit      quantity      discount
count  51290.000000  51290.000000  51290.000000  51290.000000
mean     246.498440     28.641740      3.476545      0.142908
std      487.567175    174.424113      2.278766      0.212280
min        0.000000  -6599.978000      1.000000      0.000000
25%       31.000000      0.000000      2.000000      0.000000
50%       85.000000      9.240000      3.000000      0.000000
75%      251.000000     36.810000      5.000000      0.200000
max    22638.000000   8399.976000     14.000000      0.850000

In [24]:
df['sales'] = df['sales'].str.replace(',', '').astype(float)

In [26]:
df['sales'] = df['sales'].astype(float)